/* ===========================================================================
   PORTFOLIO CONTENT — generated by admin.html on 8/12/2026, 9:25:46 PM
   Edit through the console rather than by hand where you can.
   =========================================================================== */
window.PORTFOLIO_DATA = {
  "site": {
    "hero": {
      "ios": {
        "image": "images/hero-ios.png",
        "caption": "A home screen."
      },
      "android": {
        "image": "images/hero-android.png",
        "caption": "A home screen I built."
      }
    },
    "portrait": "me.jpg"
  },
  "categories": [
    {
      "id": "mobile",
      "label": "Mobile"
    },
    {
      "id": "platform",
      "label": "Platform"
    },
    {
      "id": "ai",
      "label": "AI & Vision"
    },
    {
      "id": "new",
      "label": "new"
    }
  ],
  "projects": [
    {
      "id": "devotee",
      "name": "Devotee",
      "tagline": "A matrimonial platform built around trust, not swipes.",
      "stack": "Flutter · Firebase · Riverpod · Cloud Functions · REST",
      "categories": [
        "mobile",
        "platform"
      ],
      "gradient": "linear-gradient(165deg,#ff9a6b,#e0446f 55%,#7a2a86)",
      "links": {
        "appStore": "",
        "playStore": "https://play.google.com/store/apps/details?id=in.devoteematrimony&hl=en_US",
        "github": "https://github.com/yaksh1010"
      },
      "screenshots": []
    },
    {
      "id": "doodeg",
      "name": "Doo Deg Taxi",
      "tagline": "Live dispatch and routing for a city taxi fleet.",
      "stack": "Flutter · Google Maps SDK · REST · Realtime DB · FCM",
      "categories": [
        "mobile",
        "platform"
      ],
      "gradient": "linear-gradient(165deg,#ffd43f,#f5a208 52%,#3a2b00)",
      "links": {
        "appStore": "",
        "playStore": "",
        "github": "https://github.com/yaksh1010"
      },
      "screenshots": []
    },
    {
      "id": "arfit",
      "name": "AR Fitness",
      "tagline": "Real-time form correction using pose estimation.",
      "stack": "Unity · OpenCV · TensorFlow · Python · C#",
      "categories": [
        "ai",
        "mobile",
        "new",
        "platform"
      ],
      "gradient": "linear-gradient(165deg,#4ff0d0,#12a3ff 52%,#3b2bff)",
      "links": {
        "appStore": "",
        "playStore": "",
        "github": "https://github.com/yaksh1010"
      },
      "screenshots": [
        "images/ar-fitness-1.jpg"
      ]
    },
    {
      "id": "scan2send",
      "name": "Scan2Send",
      "tagline": "Scan, sync and send — built with a team of four.",
      "stack": "Flutter · BLoC · Cloud Storage · Background Sync",
      "categories": [
        "mobile",
        "platform"
      ],
      "gradient": "linear-gradient(165deg,#7ee6a6,#12a3ff 55%,#0a4fa8)",
      "links": {
        "appStore": "",
        "playStore": "",
        "github": ""
      },
      "screenshots": []
    },
    {
      "id": "stutrack",
      "name": "StuTrack",
      "tagline": "A study tracker with timers, streaks and progress analytics.",
      "stack": "Flutter · Firebase · Local Notifications",
      "categories": [
        "mobile"
      ],
      "gradient": "linear-gradient(165deg,#c08cff,#6b4bff 55%,#221a5c)",
      "links": {
        "appStore": "",
        "playStore": "",
        "github": ""
      },
      "screenshots": []
    },
    {
      "id": "new-project",
      "name": "New project",
      "tagline": "",
      "stack": "",
      "categories": [
        "mobile"
      ],
      "gradient": "linear-gradient(165deg,#ff9a6b,#e0446f 55%,#7a2a86)",
      "links": {
        "appStore": "",
        "playStore": "",
        "github": ""
      },
      "screenshots": [
        "images/new-project-1.png"
      ]
    }
  ],
  "experience": [
    {
      "when": "Aug 2026 — Jul 2028",
      "where": "San José, CA",
      "role": "Master of Science, Computer Science",
      "org": "San José State University",
      "badge": "Expected Jul 2028",
      "summary": "Graduate study alongside continued production work — the reason I'm targeting a Summer 2027 internship.",
      "points": [],
      "metrics": [],
      "tags": [
        "Algorithms",
        "Systems",
        "Applied ML"
      ]
    },
    {
      "when": "Jan 2026 — Jun 2026",
      "where": "Remote",
      "role": "Flutter Developer Intern",
      "org": "The Karmic Universe",
      "badge": "",
      "summary": "",
      "points": [
        "Built and shipped <b>Devotee Matrimony</b>, a cross-platform matchmaking app live on both Google Play and the App Store.",
        "Implemented OTP authentication, multi-criteria profile search, real-time in-app messaging, and granular privacy controls for user-managed profile visibility.",
        "Developed a personalised match recommendation feed and a saved-profiles system so users could track and revisit prospects."
      ],
      "metrics": [
        {
          "value": "10,000+",
          "label": "DOWNLOADS"
        },
        {
          "value": "3.8 ★",
          "label": "STORE RATING"
        },
        {
          "value": "259",
          "label": "REVIEWS"
        }
      ],
      "tags": [
        "Flutter",
        "Riverpod",
        "Firebase",
        "REST"
      ]
    },
    {
      "when": "Dec 2024 — Dec 2025",
      "where": "Vadodara, India",
      "role": "Mobile Application Developer",
      "org": "WeblogySphere Pvt. Ltd.",
      "badge": "Promoted from intern",
      "summary": "",
      "points": [
        "Shipped two production applications — <b>Scan2Send</b> and <b>WorkHive Bidding</b> — from requirements through release, leading a four-person team on Scan2Send.",
        "Integrated authentication, cloud storage and background sync so data stayed consistent in real time across devices.",
        "Profiled performance bottlenecks and refactored state management, cutting the crash rate by roughly 40%."
      ],
      "metrics": [
        {
          "value": "−40%",
          "label": "CRASH RATE"
        },
        {
          "value": "4",
          "label": "ENGINEERS LED"
        },
        {
          "value": "2",
          "label": "APPS SHIPPED"
        }
      ],
      "tags": [
        "Flutter",
        "BLoC",
        "Cloud Storage",
        "CI/CD"
      ]
    },
    {
      "when": "Jul 2023 — Jul 2026",
      "where": "Vadodara, India · Remote",
      "role": "Freelance Mobile Developer",
      "org": "Self-employed",
      "badge": "",
      "summary": "",
      "points": [
        "Designed, built and published <b>10 client applications</b> on Google Play and the App Store across transportation, food service, education, wellness and media.",
        "Delivered <b>DooDeg Taxi</b> (live driver tracking, fare estimation), <b>GreenGains</b> (real-time menus and payments) and <b>StuTrack</b> (timers, streaks, progress analytics).",
        "Owned every engagement end to end — requirements, UI, backend integration, release and post-launch maintenance."
      ],
      "metrics": [
        {
          "value": "10",
          "label": "APPS PUBLISHED"
        },
        {
          "value": "5",
          "label": "INDUSTRIES"
        },
        {
          "value": "3 yrs",
          "label": "CLIENT DELIVERY"
        }
      ],
      "tags": [
        "Flutter",
        "Google Maps",
        "Firebase",
        "Payments"
      ]
    },
    {
      "when": "Graduated May 2025",
      "where": "Vadodara, India",
      "role": "Bachelor of Science, Computer Science",
      "org": "Navrachana University",
      "badge": "GPA 3.56 / 4.0",
      "summary": "Where the freelance practice started — and kept running alongside the degree.",
      "points": [],
      "metrics": [],
      "tags": [
        "Python",
        "Java",
        "Databases"
      ]
    }
  ],
  "certifications": [
    "Cloud Foundations",
    "Cloud Security Foundations",
    "Machine Learning",
    "Natural Language Processing"
  ],
  "analytics": {
    "goatcounterCode": "yaksh1010"
  }
};
