/* ===========================================================================
   PORTFOLIO CONTENT — generated by admin.html on 8/26/2026, 9:47:03 PM
   Edit through the console rather than by hand where you can.
   =========================================================================== */
window.PORTFOLIO_DATA = {
  "site": {
    "hero": {
      "ios": {
        "image": "images/hero-ios.png",
        "caption": "A home screen."
      },
      "android": {
        "image": "images/hero-android.png",
        "caption": "A home screen I built."
      }
    },
    "portrait": "me.jpg",
    "resume": "images/resume.pdf"
  },
  "categories": [
    {
      "id": "mobile",
      "label": "Published"
    },
    {
      "id": "platform",
      "label": "Projects"
    },
    {
      "id": "ai",
      "label": "On-Going"
    }
  ],
  "projects": [
    {
      "id": "devotee",
      "name": "Devotee Matrimony",
      "tagline": "A matrimonial platform built around trust, not swipes.",
      "stack": "Flutter · Firebase · Riverpod · Cloud Functions · REST",
      "categories": [
        "mobile"
      ],
      "gradient": "linear-gradient(165deg,#ff9a6b,#e0446f 55%,#7a2a86)",
      "links": {
        "appStore": "https://apps.apple.com/in/app/devotee-matrimony/id6737876305",
        "playStore": "https://play.google.com/store/apps/details?id=in.devoteematrimony&hl=en_US",
        "github": ""
      },
      "screenshots": [
        "images/devotee-matrimony-1.png",
        "images/devotee-matrimony-2.png",
        "images/devotee-matrimony-3.png"
      ],
      "device": "phone"
    },
    {
      "id": "stutrack",
      "name": "StuTrack",
      "tagline": "AI-powered study planner and focus app with app blocking, timers, and productivity analytics.",
      "stack": "Flutter · Firebase · AI · Android Accessibility Service · Local Notifications",
      "categories": [
        "mobile"
      ],
      "gradient": "linear-gradient(165deg,#c08cff,#6b4bff 55%,#221a5c)",
      "links": {
        "appStore": "",
        "playStore": "https://play.google.com/store/apps/details?id=com.vedaira.stutrack",
        "github": "https://github.com/yaksh1010/StuTrack-Portfolio"
      },
      "screenshots": [
        "images/stutrack-1.jpeg",
        "images/stutrack-2.jpeg",
        "images/stutrack-3.jpeg",
        "images/stutrack-4.jpeg",
        "images/stutrack-5.jpeg"
      ],
      "device": "phone"
    },
    {
      "id": "doodeg",
      "name": "Doo Deg Taxi",
      "tagline": "Taxi booking and ride-tracking platform with real-time location, transparent fares, and secure payments.",
      "stack": "Flutter · Firebase · Google Maps · GPS/Location",
      "categories": [
        "mobile"
      ],
      "gradient": "linear-gradient(165deg,#ffd43f,#f5a208 52%,#3a2b00)",
      "links": {
        "appStore": "https://apps.apple.com/in/app/mithila-doo-deg-taxi/id6758665511",
        "playStore": "https://play.google.com/store/apps/details?id=com.doodeg.taxi",
        "github": ""
      },
      "screenshots": [
        "images/doo-deg-taxi-1.png",
        "images/doo-deg-taxi-2.png",
        "images/doo-deg-taxi-3.png",
        "images/doo-deg-taxi-4.png"
      ],
      "device": "phone"
    },
    {
      "id": "packarma",
      "name": "Packarma",
      "tagline": "Digital packaging platform for material selection, customized solutions, and procurement.",
      "stack": "Flutter · Firebase · REST APIs · E-Commerce · Material Catalog",
      "categories": [
        "mobile"
      ],
      "gradient": "linear-gradient(165deg,#ff9a6b,#e0446f 55%,#7a2a86)",
      "device": "phone",
      "links": {
        "appStore": "https://apps.apple.com/us/app/packarma/id1666282108",
        "playStore": "https://play.google.com/store/apps/details?id=com.packult.customer",
        "github": ""
      },
      "screenshots": [
        "images/packarma-1.png",
        "images/packarma-2.png",
        "images/packarma-3.png",
        "images/packarma-4.png",
        "images/packarma-5.png"
      ]
    },
    {
      "id": "new-project",
      "name": "ShortSee",
      "tagline": "Short-form streaming platform for binge-worthy micro-dramas and bite-sized series.",
      "stack": "Flutter · Firebase · Video Streaming · REST APIs · Android",
      "categories": [
        "mobile"
      ],
      "gradient": "linear-gradient(165deg,#ff9a6b,#e0446f 55%,#7a2a86)",
      "links": {
        "appStore": "",
        "playStore": "https://play.google.com/store/apps/details?id=com.codexlaza.surilyvideo",
        "github": ""
      },
      "screenshots": [],
      "device": "phone"
    },
    {
      "id": "scan2send",
      "name": "Scan2Send",
      "tagline": "Scan, sync and send — built with a team of four.",
      "stack": "Flutter · BLoC · Cloud Storage · Background Sync",
      "categories": [
        "platform"
      ],
      "gradient": "linear-gradient(165deg,#7ee6a6,#12a3ff 55%,#0a4fa8)",
      "links": {
        "appStore": "",
        "playStore": "",
        "github": "https://github.com/yaksh1010/Scan2Send-Portfolio"
      },
      "screenshots": [],
      "device": "phone"
    },
    {
      "id": "arfit",
      "name": "ARFit",
      "tagline": "AI-powered fitness app with AR workouts, real-time body tracking, and personalized plans.",
      "stack": "Flutter · TensorFlow · Unity AR · OpenCV · Firebase",
      "categories": [
        "platform"
      ],
      "gradient": "linear-gradient(165deg,#ff9a6b,#e0446f 55%,#7a2a86)",
      "device": "phone",
      "links": {
        "appStore": "",
        "playStore": "",
        "github": "https://github.com/yaksh1010/ARFit"
      },
      "screenshots": [
        "images/arfit-1.png",
        "images/arfit-2.png",
        "images/arfit-3.png",
        "images/arfit-4.png",
        "images/arfit-5.png"
      ]
    },
    {
      "id": "pranayama",
      "name": "Pranayama",
      "tagline": "Daily Practice of Yoga and Pranayama in Gamified Platform",
      "stack": "Flutter · Firebase · BLoC · Cloud Storage · Background Sync",
      "categories": [
        "platform"
      ],
      "gradient": "linear-gradient(165deg,#ff9a6b,#e0446f 55%,#7a2a86)",
      "device": "phone",
      "links": {
        "appStore": "",
        "playStore": "",
        "github": ""
      },
      "screenshots": [
        "images/pranayama-1.png",
        "images/pranayama-2.png",
        "images/pranayama-3.png",
        "images/pranayama-4.png",
        "images/pranayama-5.png",
        "images/pranayama-6.png"
      ]
    }
  ],
  "experience": [
    {
      "when": "Aug 2026 — Jul 2028",
      "where": "San José, CA",
      "role": "Master of Science, Computer Science",
      "org": "San José State University",
      "badge": "Expected Jul 2028",
      "summary": "Graduate study alongside continued production work — the reason I'm targeting a Summer 2027 internship.",
      "points": [],
      "metrics": [],
      "tags": [
        "Algorithms",
        "Systems",
        "Applied ML",
        "GenAI",
        "Cloud"
      ]
    },
    {
      "when": "Jan 2026 — Jun 2026",
      "where": "Remote",
      "role": "Flutter Developer",
      "org": "The Karmic Universe",
      "badge": "",
      "summary": "",
      "points": [
        "Built and shipped <b>Devotee Matrimony</b>, a cross-platform matchmaking app live on both Google Play and the App Store.",
        "Implemented OTP authentication, multi-criteria profile search, real-time in-app messaging, and granular privacy controls for user-managed profile visibility.",
        "Developed a personalised match recommendation feed and a saved-profiles system so users could track and revisit prospects."
      ],
      "metrics": [
        {
          "value": "10,000+",
          "label": "DOWNLOADS"
        },
        {
          "value": "4 ★",
          "label": "STORE RATING"
        },
        {
          "value": "231",
          "label": "REVIEWS"
        }
      ],
      "tags": [
        "Flutter",
        "Riverpod",
        "Firebase",
        "REST"
      ]
    },
    {
      "when": "Dec 2024 — Dec 2025",
      "where": "Vadodara, India",
      "role": "Mobile Application Developer",
      "org": "WeblogySphere Pvt. Ltd.",
      "badge": "Promoted from intern",
      "summary": "",
      "points": [
        "Shipped two production applications — <b>Scan2Send</b> and <b>WorkHive Bidding</b> — from requirements through release, leading a four-person team on Scan2Send.",
        "Integrated authentication, cloud storage and background sync so data stayed consistent in real time across devices.",
        "Profiled performance bottlenecks and refactored state management, cutting the crash rate by roughly 40%."
      ],
      "metrics": [
        {
          "value": "−40%",
          "label": "CRASH RATE"
        },
        {
          "value": "4",
          "label": "ENGINEERS LED"
        },
        {
          "value": "2",
          "label": "APPS SHIPPED"
        }
      ],
      "tags": [
        "Flutter",
        "BLoC",
        "Cloud Storage",
        "CI/CD"
      ]
    },
    {
      "when": "Jul 2023 — Jul 2026",
      "where": "Vadodara, India · Remote",
      "role": "Freelance Mobile Developer",
      "org": "Self-employed",
      "badge": "",
      "summary": "",
      "points": [
        "Designed, built and published <b>10+ client applications</b> on Google Play and the App Store across transportation, food service, education, wellness and media.",
        "Delivered <b>DooDeg Taxi</b> (live driver tracking, fare estimation), <b>GreenGains</b> (real-time menus and payments) and <b>StuTrack</b> (timers, streaks, progress analytics).",
        "Owned every engagement end to end — requirements, UI, backend integration, release and post-launch maintenance."
      ],
      "metrics": [
        {
          "value": "10+",
          "label": "APPS SHIPPED"
        },
        {
          "value": "5",
          "label": "INDUSTRIES"
        },
        {
          "value": "3 yrs",
          "label": "CLIENT DELIVERY"
        }
      ],
      "tags": [
        "Flutter",
        "Google Maps",
        "Firebase",
        "Payments"
      ]
    },
    {
      "when": "Graduated May 2025",
      "where": "Vadodara, India",
      "role": "Bachelor of Science, Computer Science",
      "org": "Navrachana University",
      "badge": "GPA 3.56 / 4.0",
      "summary": "Where the freelance practice started — and kept running alongside the degree.",
      "points": [],
      "metrics": [],
      "tags": [
        "Python",
        "Java",
        "Databases"
      ]
    }
  ],
  "certifications": [
    "Cloud Foundations",
    "Cloud Security Foundations",
    "Machine Learning",
    "Natural Language Processing"
  ],
  "analytics": {
    "goatcounterCode": "yaksh1010"
  }
};
